apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: final
  labels:
    app: mysql
    component: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      component: database
  template:
    metadata:
      labels:
        app: mysql
        component: database
    spec:
      containers:
      - name: mysql-container
        image: 892915606637.dkr.ecr.us-east-1.amazonaws.com/clo835_project_repository_mysql:latest
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secrets
                key: MYSQL_ROOT_PASSWORD
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: mysql-persistent
            mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent
        persistentVolumeClaim:
          claimName: mysql-pvc