apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: employees
    component: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees
      component: webapp
  template:
    metadata:
      labels:
        app: employees
        component: webapp
    spec:
      containers:
      - image: 610510370017.dkr.ecr.us-east-1.amazonaws.com/clo835_project_repository_webapp:v1.1
        name: webapp-container
        ports:
        - containerPort: 81
        env:
        - name: DBPWD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_ROOT_PASSWORD
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: DBUSER
        - name: DBHOST
          value: "mysql-service.final.svc.cluster.local"
        - name: DBPORT
          value: "3306"
