apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-rolebinding
  namespace: final
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: clo835-role
subjects:
  - kind: ServiceAccount
    name: clo835
    namespace: final
    apiGroup: ""