apiVersion: v1
kind: Service
metadata:
  name: webapp-service
  labels:
    app: employees
    component: webapp
spec:
  type: LoadBalancer  
  ports:
  - port: 81
    targetPort: 81
  selector:
    app: employees
      